### ISSUE TITLE
Inquiry Regarding Object and Motion Trajectory Generation

### ISSUE THREAD

**Issue by ZWanG0802** [zdchan/GraspXL#6]
Sorry to bother you. When I tried to introduce my own object to generate a motion trajectory, I noticed that the hand remains stationary and does not move, and the distance from the target point I set is quite far. Could this be an issue with the URDF or OBJ model imports? I hope to receive your guidance.

**Comment by ZWanG0802** [comment]
The situation is shown in the attached image.
![22d3fa54dd8609fb168222b13a3d0e6](https://github.com/user-attachments/assets/b54c89c7-9bf5-49d2-bd0d-faf9e238cfa1)
![38470548560ceb31c5b9026786b9b1a](https://github.com/user-attachments/assets/1df45c85-5aca-43f6-bc90-9af50db56e76)

**Comment by zdchan** [comment]
Hi you can check the collision bodies in UI to see what happened that the hand does not move. You cannot just replace the mesh file of the object.  I will soon upload a script for formatting the new objects.

**Comment by ZWanG0802** [comment]
Thank you very much! When I checked the collision body, I indeed found the problem: the collision bodies are significantly larger than the visual bodies.

> Hi you can check the collision bodies in UI to see what happened that the hand does not move. You cannot just replace the mesh file of the object. I will soon upload a script for formatting the new objects.

**Comment by zdchan** [comment]
That's the problem. You need to scale the object (.obj file) to a meaningful size. Then run the script I have just released [urdf_gen.py](./raisimGymTorch/raisimGymTorch/helper/URDF_gen_from_obj/urdf_gen.py) to generate the urdf.

**Comment by ZWanG0802** [comment]
After I modified the values of the collision body, the situation did improve, but I'm still encountering the issue where the hand moves in the opposite direction. Do you know what might be causing this?
![58434a26a8ed5ba9f4213067001566e](https://github.com/user-attachments/assets/737766ad-be91-4b72-8bca-b298169dd13d)


> That's the problem. You need to scale the object (.obj file) to a meaningful size. Then run the script I have just released [urdf_gen.py](https://github.com/zdchan/GraspXL/blob/main/raisimGymTorch/raisimGymTorch/helper/URDF_gen_from_obj/urdf_gen.py) to generate the urdf.

**Comment by zdchan** [comment]
check the collision between the hand and the table. The hand seems stuck in the table.

**Comment by ZWanG0802** [comment]
> check the collision between the hand and the table. The hand seems stuck in the table.

How should I address this issue? I tried comparing my URDF file with the demo's URDF file but couldn't find any clues. This problem has been bothering me for a long time. I’m very sorry to trouble you again.
![屏幕截图 2024-10-19 205804](https://github.com/user-attachments/assets/46dd4b09-dc00-4901-b936-fed4bff1b31b)
and URDF files as follow:
```c
<?xml version='1.0' encoding='UTF-8'?>
<robot name="partnet_1133b046-84e1-40d4-ab94-548fe59fb8f0">
	
	<link name="link_0">
		
		
		<visual name="other_leaf-13">
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0.2005842114635701 0.02750199361465766 0.012073427209372878" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-10.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</visual>
		
		
		<visual name="other_leaf-13">
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0.2005842114635701 0.02750199361465766 0.012073427209372878" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-8.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</visual>
		
		
		<visual name="other_leaf-13">
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0.2005842114635701 0.02750199361465766 0.012073427209372878" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-9.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</visual>
		
		
		<visual name="blade-4">
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0.2005842114635701 0.02750199361465766 0.012073427209372878" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-4.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</visual>
		
		
		<visual name="blade-4">
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0.2005842114635701 0.02750199361465766 0.012073427209372878" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-3.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</visual>
		
		
		<visual name="handle-5">
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0.2005842114635701 0.02750199361465766 0.012073427209372878" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-26.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</visual>
		
		
		<visual name="handle-5">
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0.2005842114635701 0.02750199361465766 0.012073427209372878" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-27.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</visual>
		
		
		<visual name="handle-5">
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0.2005842114635701 0.02750199361465766 0.012073427209372878" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-28.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</visual>
		
		
		<collision>
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0.2005842114635701 0.02750199361465766 0.012073427209372878" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-10.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</collision>
		
		
		<collision>
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0.2005842114635701 0.02750199361465766 0.012073427209372878" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-8.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</collision>
		
		
		<collision>
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0.2005842114635701 0.02750199361465766 0.012073427209372878" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-9.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</collision>
		
		
		<collision>
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0.2005842114635701 0.02750199361465766 0.012073427209372878" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-4.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</collision>
		
		
		<collision>
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0.2005842114635701 0.02750199361465766 0.012073427209372878" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-3.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</collision>
		
		
		<collision>
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0.2005842114635701 0.02750199361465766 0.012073427209372878" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-26.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</collision>
		
		
		<collision>
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0.2005842114635701 0.02750199361465766 0.012073427209372878" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-27.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</collision>
		
		
		<collision>
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0.2005842114635701 0.02750199361465766 0.012073427209372878" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-28.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</collision>
		
	
		<inertial>
			<origin rpy="0 0 0" xyz="0 0 0" />
			<mass value="0.9068886315840093" />
			<inertia ixx="0.9" ixy="0.9" ixz="0.9" iyy="0.9" iyz="0.9" izz="0.9" />
		</inertial>
	</link>
	
	
	<joint name="joint_0" type="revolute">
		
		
		<origin rpy="0.0 0.0 0.0" xyz="-0.2005842114635701 -0.02750199361465766 -0.012073427209372878" />
		
		
		<axis xyz="0 -1 0" />
		
		
		<child link="link_0" />
		
		
		<parent link="link_1" />
		<dynamics damping="1.0" friction="1.0"/>
		<limit lower="-0.1759291886010284" upper="-0.0" effort="0.1" velocity="0.1" />
		
	
	</joint>
	
	
	<link name="link_1">
		
		
		<visual name="screw-3">
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-1.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</visual>
		
		
		<visual name="screw-3">
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-24.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</visual>
		
		
		<visual name="screw-3">
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-16.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</visual>
		
		
		<visual name="screw-3">
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-5.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</visual>
		
		
		<visual name="other_leaf-11">
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-15.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</visual>
		
		
		<visual name="other_leaf-11">
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-13.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</visual>
		
		
		<visual name="other_leaf-11">
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-14.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</visual>
		
		
		<visual name="blade-6">
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-23.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</visual>
		
		
		<visual name="blade-6">
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-22.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</visual>
		
		
		<visual name="handle-7">
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-18.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</visual>
		
		
		<visual name="handle-7">
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-20.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</visual>
		
		
		<visual name="handle-7">
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-19.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</visual>
		
		
		<collision>
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-1.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</collision>
		
		
		<collision>
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-24.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</collision>
		
		
		<collision>
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-16.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</collision>
		
		
		<collision>
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-5.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</collision>
		
		
		<collision>
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-15.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</collision>
		
		
		<collision>
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-13.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</collision>
		
		
		<collision>
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-14.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</collision>
		
		
		<collision>
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-23.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</collision>
		
		
		<collision>
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-22.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</collision>
		
		
		<collision>
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-18.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</collision>
		
		
		<collision>
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-20.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</collision>
		
		
		<collision>
			
			
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0" />
			
			
			<geometry>
				
				
				<mesh filename="textured_objs/original-19.obj" scale="0.15 0.15 0.15" />
				
			
			</geometry>
			
		
		</collision>
		
	
		<inertial>
			<origin rpy="0 0 0" xyz="0 0 0" />
			<mass value="0.8674313574914879" />
			<inertia ixx="0.9" ixy="0.9" ixz="0.9" iyy="0.9" iyz="0.9" izz="0.9" />
		</inertial>
	</link>
	
	
	

</robot>
```

**Comment by zdchan** [comment]
Our system aims for objects with specific urdf formats, that's why we released the pre-processing scripts. You cannot just put a random urdf file there for grasping. I am not quite sure what caused the problem though.

**Comment by ZWanG0802** [comment]
> Our system aims for objects with specific urdf formats, that's why we released the pre-processing scripts. You cannot just put a random urdf file there for grasping. I am not quite sure what caused the problem though, but I am quite sure this urdf won't work as the object, as the policy is set to grasp the link with a specific name in simulation. Sorry that I cannot help more with this.

Thank you very much for your help ：). After I refactored the URDF script, the problem was resolved.
